allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma

overrides:
  tailwind-merge: "^3.6.0"
  reselect: "^5.2.0"
  semver: "^7.7.1"

strictDepBuilds: true
minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
