// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add -D prisma
import { defineConfig } from "prisma/config";

// Load .env for local development only when DATABASE_URL is not set as an env var
if (!process.env.DATABASE_URL) {
  require("dotenv/config");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
